project 'Sample.xcodeproj'

# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'


target 'Sample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  

  pod 'Countly', '~> 19.08'
  pod 'YYKit', '~>1.0.9'

end
